//This file is generated by CODE GEN Version 1 on Tue Jan 3 18:20:58 2017
//Atul Sharma
#include "batteryinfo.h"

BatteryInfo::BatteryInfo(){

}

void BatteryInfo::setName(QString val){
	mName = val ;
}

void BatteryInfo::setStatus(QString val){
	mStatus = val ;
}

void BatteryInfo::setSupplyPresent(int val){
	mSupplyPresent = val ;
}

void BatteryInfo::setSupplyTechnology(QString val){
	mSupplyTechnology = val ;
}

void BatteryInfo::setSupplyCycleCount(quint64 val){
	mSupplyCycleCount = val ;
}

void BatteryInfo::setSupplyVoltageMinDesign(quint64 val){
	mSupplyVoltageMinDesign = val ;
}

void BatteryInfo::setSupplyVoltageNow(quint64 val){
	mSupplyVoltageNow = val ;
}

void BatteryInfo::setSupplyCurrentNow(quint64 val){
	mSupplyCurrentNow = val ;
}

void BatteryInfo::setSupplyChargeFullDesign(quint64 val){
	mSupplyChargeFullDesign = val ;
}

void BatteryInfo::setSupplyChargeFull(quint64 val){
	mSupplyChargeFull = val ;
}

void BatteryInfo::setSupplyChargeNow(quint64 val){
	mSupplyChargeNow = val ;
}

void BatteryInfo::setSupplyCapacity(quint64 val){
	mSupplyCapacity = val ;
}

void BatteryInfo::setSupplyCapacityLevel(QString val){
	mSupplyCapacityLevel = val ;
}

void BatteryInfo::setSupplyModelName(QString val){
	mSupplyModelName = val ;
}

void BatteryInfo::setSupplyManufacturer(QString val){
	mSupplyManufacturer = val ;
}

QString BatteryInfo::getName () const{
	return this->mName;
}

QString BatteryInfo::getStatus () const{
	return this->mStatus;
}

int BatteryInfo::getSupplyPresent () const{
	return this->mSupplyPresent;
}

QString BatteryInfo::getSupplyTechnology () const{
	return this->mSupplyTechnology;
}

quint64 BatteryInfo::getSupplyCycleCount () const{
	return this->mSupplyCycleCount;
}

quint64 BatteryInfo::getSupplyVoltageMinDesign () const{
	return this->mSupplyVoltageMinDesign;
}

quint64 BatteryInfo::getSupplyVoltageNow () const{
	return this->mSupplyVoltageNow;
}

quint64 BatteryInfo::getSupplyCurrentNow () const{
	return this->mSupplyCurrentNow;
}

quint64 BatteryInfo::getSupplyChargeFullDesign () const{
	return this->mSupplyChargeFullDesign;
}

quint64 BatteryInfo::getSupplyChargeFull () const{
	return this->mSupplyChargeFull;
}

quint64 BatteryInfo::getSupplyChargeNow () const{
	return this->mSupplyChargeNow;
}

quint64 BatteryInfo::getSupplyCapacity () const{
	return this->mSupplyCapacity;
}

QString BatteryInfo::getSupplyCapacityLevel () const{
	return this->mSupplyCapacityLevel;
}

QString BatteryInfo::getSupplyModelName () const{
	return this->mSupplyModelName;
}

QString BatteryInfo::getSupplyManufacturer () const{
	return this->mSupplyManufacturer;
}

void BatteryInfo::showInfo(){
    qDebug() << "------------------Battery Info -------------------";
    qDebug() << "POWER_SUPPLY_NAME. . . . . . . . : " << getName();
    qDebug() << "POWER_SUPPLY_STATUS. . . . . . . : " << getStatus();
    qDebug() << "POWER_SUPPLY_PRESENT . . . . . . : " << getSupplyPresent();
    qDebug() << "POWER_SUPPLY_TECHNOLOGY. . . . . : " << getSupplyTechnology();
    qDebug() << "POWER_SUPPLY_CYCLE_COUNT . . . . : " << getSupplyCycleCount();
    qDebug() << "POWER_SUPPLY_VOLTAGE_MIN_DESIGN. : " << getSupplyVoltageMinDesign();
    qDebug() << "POWER_SUPPLY_VOLTAGE_NOW . . . . : " << getSupplyVoltageNow();
    qDebug() << "POWER_SUPPLY_CURRENT_NOW . . . . : " << getSupplyCurrentNow();
    qDebug() << "POWER_SUPPLY_CHARGE_FULL_DESIGN. : " << getSupplyChargeFullDesign();
    qDebug() << "POWER_SUPPLY_CHARGE_FULL . . . . : " << getSupplyChargeFull();
    qDebug() << "POWER_SUPPLY_CHARGE_NOW  . . . . : " << getSupplyChargeNow();
    qDebug() << "POWER_SUPPLY_CAPACITY. . . . . . : " << getSupplyCapacity();
    qDebug() << "POWER_SUPPLY_CAPACITY_LEVEL. . . : " << getSupplyCapacityLevel();
    qDebug() << "POWER_SUPPLY_MODEL_NAME. . . . . : " << getSupplyModelName();
    qDebug() << "POWER_SUPPLY_MANUFACTURER. . . . : " << getSupplyManufacturer();
    qDebug() << "--------------------------------------------------";


}

